from tkinter import *
parent=Tk()
redbutton=Button(parent,text="Red",fg="red")
redbutton.pack(side=LEFT)
greenbutton= Button(parent,text="Green",fg="green")
greenbutton.pack(side="right",fill="x")
bluebutton = Button(parent,text="Blue",fg="blue")
bluebutton.pack(side="top")
blackbutton=Button(parent,text="Black",fg="black")
blackbutton.pack(side=BOTTOM)
parent.mainloop()